[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[dev]
  functionsPort = 8890
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "./netlify/functions/api/:splat"